/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as MyFlightsRouteImport } from './routes/my-flights'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FlightPlanRouteImport } from './routes/flight-plan'
import { Route as ChartsRouteImport } from './routes/charts'
import { Route as AtisRouteImport } from './routes/atis'
import { Route as AtcRouteImport } from './routes/atc'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartnersSlugRouteImport } from './routes/partners.$slug'
import { Route as ApiPublicDiscordLoginRouteImport } from './routes/api/public/discord/login'
import { Route as ApiPublicDiscordCallbackRouteImport } from './routes/api/public/discord/callback'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const MyFlightsRoute = MyFlightsRouteImport.update({
  id: '/my-flights',
  path: '/my-flights',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FlightPlanRoute = FlightPlanRouteImport.update({
  id: '/flight-plan',
  path: '/flight-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartsRoute = ChartsRouteImport.update({
  id: '/charts',
  path: '/charts',
  getParentRoute: () => rootRouteImport,
} as any)
const AtisRoute = AtisRouteImport.update({
  id: '/atis',
  path: '/atis',
  getParentRoute: () => rootRouteImport,
} as any)
const AtcRoute = AtcRouteImport.update({
  id: '/atc',
  path: '/atc',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersSlugRoute = PartnersSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PartnersRoute,
} as any)
const ApiPublicDiscordLoginRoute = ApiPublicDiscordLoginRouteImport.update({
  id: '/api/public/discord/login',
  path: '/api/public/discord/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDiscordCallbackRoute =
  ApiPublicDiscordCallbackRouteImport.update({
    id: '/api/public/discord/callback',
    path: '/api/public/discord/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atc': typeof AtcRoute
  '/atis': typeof AtisRoute
  '/charts': typeof ChartsRoute
  '/flight-plan': typeof FlightPlanRoute
  '/login': typeof LoginRoute
  '/my-flights': typeof MyFlightsRoute
  '/partners': typeof PartnersRouteWithChildren
  '/voice': typeof VoiceRoute
  '/partners/$slug': typeof PartnersSlugRoute
  '/api/public/discord/callback': typeof ApiPublicDiscordCallbackRoute
  '/api/public/discord/login': typeof ApiPublicDiscordLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atc': typeof AtcRoute
  '/atis': typeof AtisRoute
  '/charts': typeof ChartsRoute
  '/flight-plan': typeof FlightPlanRoute
  '/login': typeof LoginRoute
  '/my-flights': typeof MyFlightsRoute
  '/partners': typeof PartnersRouteWithChildren
  '/voice': typeof VoiceRoute
  '/partners/$slug': typeof PartnersSlugRoute
  '/api/public/discord/callback': typeof ApiPublicDiscordCallbackRoute
  '/api/public/discord/login': typeof ApiPublicDiscordLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atc': typeof AtcRoute
  '/atis': typeof AtisRoute
  '/charts': typeof ChartsRoute
  '/flight-plan': typeof FlightPlanRoute
  '/login': typeof LoginRoute
  '/my-flights': typeof MyFlightsRoute
  '/partners': typeof PartnersRouteWithChildren
  '/voice': typeof VoiceRoute
  '/partners/$slug': typeof PartnersSlugRoute
  '/api/public/discord/callback': typeof ApiPublicDiscordCallbackRoute
  '/api/public/discord/login': typeof ApiPublicDiscordLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atc'
    | '/atis'
    | '/charts'
    | '/flight-plan'
    | '/login'
    | '/my-flights'
    | '/partners'
    | '/voice'
    | '/partners/$slug'
    | '/api/public/discord/callback'
    | '/api/public/discord/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atc'
    | '/atis'
    | '/charts'
    | '/flight-plan'
    | '/login'
    | '/my-flights'
    | '/partners'
    | '/voice'
    | '/partners/$slug'
    | '/api/public/discord/callback'
    | '/api/public/discord/login'
  id:
    | '__root__'
    | '/'
    | '/atc'
    | '/atis'
    | '/charts'
    | '/flight-plan'
    | '/login'
    | '/my-flights'
    | '/partners'
    | '/voice'
    | '/partners/$slug'
    | '/api/public/discord/callback'
    | '/api/public/discord/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtcRoute: typeof AtcRoute
  AtisRoute: typeof AtisRoute
  ChartsRoute: typeof ChartsRoute
  FlightPlanRoute: typeof FlightPlanRoute
  LoginRoute: typeof LoginRoute
  MyFlightsRoute: typeof MyFlightsRoute
  PartnersRoute: typeof PartnersRouteWithChildren
  VoiceRoute: typeof VoiceRoute
  ApiPublicDiscordCallbackRoute: typeof ApiPublicDiscordCallbackRoute
  ApiPublicDiscordLoginRoute: typeof ApiPublicDiscordLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-flights': {
      id: '/my-flights'
      path: '/my-flights'
      fullPath: '/my-flights'
      preLoaderRoute: typeof MyFlightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flight-plan': {
      id: '/flight-plan'
      path: '/flight-plan'
      fullPath: '/flight-plan'
      preLoaderRoute: typeof FlightPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charts': {
      id: '/charts'
      path: '/charts'
      fullPath: '/charts'
      preLoaderRoute: typeof ChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atis': {
      id: '/atis'
      path: '/atis'
      fullPath: '/atis'
      preLoaderRoute: typeof AtisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atc': {
      id: '/atc'
      path: '/atc'
      fullPath: '/atc'
      preLoaderRoute: typeof AtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/$slug': {
      id: '/partners/$slug'
      path: '/$slug'
      fullPath: '/partners/$slug'
      preLoaderRoute: typeof PartnersSlugRouteImport
      parentRoute: typeof PartnersRoute
    }
    '/api/public/discord/login': {
      id: '/api/public/discord/login'
      path: '/api/public/discord/login'
      fullPath: '/api/public/discord/login'
      preLoaderRoute: typeof ApiPublicDiscordLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/discord/callback': {
      id: '/api/public/discord/callback'
      path: '/api/public/discord/callback'
      fullPath: '/api/public/discord/callback'
      preLoaderRoute: typeof ApiPublicDiscordCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PartnersRouteChildren {
  PartnersSlugRoute: typeof PartnersSlugRoute
}

const PartnersRouteChildren: PartnersRouteChildren = {
  PartnersSlugRoute: PartnersSlugRoute,
}

const PartnersRouteWithChildren = PartnersRoute._addFileChildren(
  PartnersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtcRoute: AtcRoute,
  AtisRoute: AtisRoute,
  ChartsRoute: ChartsRoute,
  FlightPlanRoute: FlightPlanRoute,
  LoginRoute: LoginRoute,
  MyFlightsRoute: MyFlightsRoute,
  PartnersRoute: PartnersRouteWithChildren,
  VoiceRoute: VoiceRoute,
  ApiPublicDiscordCallbackRoute: ApiPublicDiscordCallbackRoute,
  ApiPublicDiscordLoginRoute: ApiPublicDiscordLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
